### ISSUE TITLE
Incomplete boxes in substitution window (Arch Linux)

### ISSUE THREAD

**Issue by teacher4711** [jcryptool/core#134]
In Version 1.0.0 (Weekly-Build--2019-01-12) in the substitution window the boxes are not displayed fully, i.e. the right margin is missing.
You therefore cannot see the letters that you either write into the boxes or select with the triangle below the boxes.
Version 0.9.9.3 displays the boxes fully.
One picture attached shows an incomplete red border around the first box which is incomplete on the right hand side, the other shows version 0.9.9.3, which displays them correctly.

![jcryptool_substitution0993](https://user-images.githubusercontent.com/6697859/51555502-062c8300-1e78-11e9-956a-a0aad1e11374.png)
![jcryptool_substitution_1000](https://user-images.githubusercontent.com/6697859/51555504-06c51980-1e78-11e9-9c1b-48b58cd24b58.png)

**Comment by grthor** [comment]
Hi, thank you for reporting the error. I will take a further look at this. Did you enter a letter in the field with the red border on the second screenshot?

@simlei maybe you can try to reproduce the bug. It works with Windows and i do not have a linux machine.

**Comment by simlei** [comment]
Wrong repository -- moved to https://github.com/jcryptool/crypto/issues/260

**Comment by simlei** [comment]
This issue is concerned with `Algorithms>Classic>Substitution`.
I actually can not reproduce: 
![image](https://user-images.githubusercontent.com/982379/66712925-61a2f600-eda4-11e9-8424-ebcdbb5cf8f8.png)
I am under 4.18.0-25-generic x86_64 GNU/Linux - Ubuntu 18.10


@teacher4711 would it be possible for you to re-evaluate whether the issue you experienced in your [original report](https://github.com/jcryptool/core/issues/134) is still around in our [latest weekly build](https://github.com/jcryptool/core/releases/)?
