### ISSUE TITLE
Java compiler compliance level should be specified by each plug-in, not by workspace

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#170]
The JCrypTool projects currently leave the choice of compiler compliance setting to the workspace default. This is potential for confusion of new developers when initializing an eclipse workspace, when the wrong compliance level is selected (even though an adequate JRE were configured!).

Projects already specify the required Java version in their classpath/manifest, so there is no reason to leave the choice of compiler compliance to the global workspace settings.

Right now, e.g. when switching to Java 8 from a system-wide default of Java 11, the following change is required in the workspace:

![image](https://user-images.githubusercontent.com/982379/74035820-514e0100-49bb-11ea-84f6-b5ff04f43466.png)

Without it, the JCT application does not launch:
![image](https://user-images.githubusercontent.com/982379/74036092-e51fcd00-49bb-11ea-8e97-af315df424ea.png)

**Comment by grthor** [comment]
I agree. It is definitely better to use the plug-in specific settings.

I just watched the Getting started tutorial and it says to set the compiler compliance level to "Use default compliance settings". So theoretically everyone is already doing that :D

https://github.com/jcryptool/core/wiki/Getting-started-as-a-JCrypTool-Developer#setting-up-your-workspace

**Comment by simlei** [comment]
> I just watched the Getting started tutorial and it says to set the compiler compliance level to "Use default compliance settings". So theoretically everyone is already doing that :D

Does it not rather say, "Locate the Java compliance level drop down box and set it to 1.8"?

**Comment by grthor** [comment]
Yes, but the checkbox at "Use default compliance settings" is also set.

Or maybe I just misunderstand the issue. It is about using the Compiler Compliance Level, which is defined in the Classpaths. To use this level you have to set the checkbox at "Use default compliance settings". If you don't do that, the level you can specify in the dropdown menus below will be used.

Am I right?

**Comment by grthor** [comment]
Ok, I was wrong, forget what I wrote. The tutorial clearly says you should set the default level to 1.8 and not use the settings from the classpath.

What do I have to change in the settings to use the compliance settings from Classpath?

**Comment by simlei** [comment]
When I complete this issue, I think that this paragraph can be removed from the guide altogether because the single plug-ins will configure their compliance level themselves, i.e. disregard workspace settings, as they do with JRE version already.

Drawback is, that all new sub-projects have to be configured that way (OK I think, same as JRE version), and that when updating the JRE, all projects have to update their settings (OK, since infrequent, and "expert" task)

**Comment by grthor** [comment]
Hi Simon, 

i am currently working on setting the default compiler compliance level to Java 11 on a project-specific basis. 

Now I am faced with the question whether I should specify the JRE in the classpath or in the modulepath. I have tried both and both worked. But in the code there is a difference in the .classpath files.
This is what it looks like when you specify the JRE in classpath:
```<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-11"/>```

and this is what it looks like when you specify it in the modulepath:
```	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-11">
		<attributes>
			<attribute name="module" value="true"/>
		</attributes>
	</classpathentry>
```

The difference is that eclipse adds an attribute ```<attribute name="module" value="true"/>```.

Do you know if there are any advantages to specifying the JRE in the classpath or the modulepath? The internet is not very helpful at this point.

If you don't know either, I would put it in the classpath, since we use it so far and there is less code (the attribute is missing).

**Comment by simlei** [comment]
AFAIK eclipse does not mind whether the JRE is configured on the classpath or on the module path; it will internally treat it as if it were put on the module path. classpath and module path are different as to when something is on the module path, one can only access public API, among other things (modules are a higher level concept than the classpath).

**Comment by grthor** [comment]
Ok thx. I will specify it in the classpath then.

**Comment by grthor** [comment]
With https://github.com/jcryptool/core/commit/8d9a471bd7ec4074d91b29f0fbecd0b793eba823 the projects in the core repo and with https://github.com/jcryptool/crypto/commit/d4b772ceaf08c259de21933216b9dc3d4bd3e3a7 the projects in the crypto repo moved to Java 11 as execution environment.

**Comment by grthor** [comment]
Since this issue has been fixed by the commits https://github.com/jcryptool/crypto/commit/d4b772ceaf08c259de21933216b9dc3d4bd3e3a7 and https://github.com/jcryptool/core/commit/8d9a471bd7ec4074d91b29f0fbecd0b793eba823, I close the issue.

**The compiler compliance level is determined by the plugins (projects).** 

A change of the level by the developer is no longer necessary. The Eclipse IDE is also set to use the compiler compliance level of the projects by default instead of the general level which can be set manually in the preferences.
