### ISSUE TITLE
Tycho version 1.6.0 in org.jcryptool.releng/pom.xml breaks build

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#171]
Solved for now by reverting to Tycho 1.5.1, but this should be addressed.

**Comment by grthor** [comment]
This problem is known and already fixed https://bugs.eclipse.org/bugs/show_bug.cgi?id=559148.

I think if we want to use tycho 1.6.0 we have to update to Eclipse 2020-03. However, the fact that we use the fix for the links from the context help to the online help for Eclipse 2019-09 speaks against this.

I would suggest we continue using Tycho 1.5.1 and discuss this point after the release of JCT 1.0.0.

**Comment by grthor** [comment]
The problem has been fixed https://bugs.eclipse.org/bugs/show_bug.cgi?id=559148#c4. Now there is still the question when the fix will be released.

**Comment by grthor** [comment]
Updated to Tycho 1.7.0 which includes the fix.

Tested the build on Linux and Windows, both work.

Problem successfully solved itself 😄
