### ISSUE TITLE
Failed to create Java Virtual Machine

### ISSUE THREAD

**Issue by wdamon** [jcryptool/core#182]
Hello,

I recently tried installing JCrypTool and it failed with an error "Failed to create Java Virtual Machine".  I am running java version "14" 2020-03-17
Java(TM) SE Runtime Environment (build 14+36-1461)
Java HotSpot(TM) 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

**Comment by simlei** [comment]
Hi! Thanks for reporting this. I'd be happy to help; which operating system are you on?

**Comment by simlei** [comment]
Hi! Thanks for reporting this. I'd be happy to help as I have recently worked on JVM changes.

First off:
- Which operating system are you on? 
- Where did you download JCT from? I'm asking the latter because I need to know whether it is a recent "weekly" build or an older, "stable" build.

**Comment by wdamon** [comment]
Hi ! Thanks for helping :) I'm on mac osx Catalina. It's a stable build i think, I downloaded it from here: https://www.cryptool.org/en/jct-downloads/stable.

**Comment by simlei** [comment]
Hi, 
its possible that this does not work any more. The stable build is actually more than two years old. 
We are in the process of finishing version 1.0 these months by the way.
Good news is, we ship our own JRE now and stability and functionality has much improved since the last "stable" build actually. I think you will enjoy the latest weekly build more than the stable version. It is here:

https://github.com/jcryptool/core/releases/tag/Weekly-Build--2020-03-21

Please take into account the note to OS/X users, but I'd be interested to hear if it works even without that line.

**Comment by wdamon** [comment]
Thanks again for all your help, the version you suggested i use worked just fine. I did have to use the suggested command to get it to work..

Much appreciated!

Will
