### ISSUE TITLE
External links in help

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#197]
Some external links in the JCT online help do not work. This is probably due to these websites having disabled embedding in iframes.

see:
    - https://github.com/jcryptool/crypto/issues/294

**Comment by grthor** [comment]
I don't know if we have made a decision on this point in the Telco. 

The following options are available for decision: 
1. look through all links and test if they can be opened in the JCT Browser. Only the links that cannot be opened can be opened in the user's standard browser. The effort here is very high, because all links have to be looked through.
2. change all links (via regex for example) so that they are opened in the standard browser. The effort for this is much less than for solution 1 and all links would open uniformly.
3. open only the links we know do not work with `target="_blank"` in the default browser. The effort would be very small. The disadvantage is that the behavior when opening links would then be different.

I would prefer solution 2, but if it is not desired that all links are opened in the standard browser and not in the JCT browser, I would prefer solution 3. I see it as too much effort for the possible benefit to look through all links as in solution 1.

What do you think about it @be4 and @simlei.

**Comment by be4** [comment]
I prefer option #2.
BE


Am 03.06.2020 um 21:30 schrieb Thorben Groos:
> I don't know if we have made a decision on this point in the Telco. 
>
> The following options are available for decision: 
> 1. look through all links and test if they can be opened in the JCT Browser. Only the links that cannot be opened can be opened in the user's standard browser. The effort here is very high, because all links have to be looked through.
> 2. change all links (via regex for example) so that they are opened in the standard browser. The effort for this is much less than for solution 1 and all links would open uniformly.
> 3. open only the links we know do not work with target="_blank" in the default browser. The effort would be very small. The disadvantage is that the behavior when opening links would then be different.
>
> I would prefer solution 2, but if it is not desired that all links are opened in the standard browser and not in the JCT browser, I would prefer solution 3. I see it as too much effort for the possible benefit to look through all links as in solution 1.
>
> What do you think about @be4 and @simlei.
>

**Comment by simlei** [comment]
Option 2 then.

**Comment by grthor** [comment]
@simlei as our regex master, can you try this? If you don't have the time, I can also try it.

**Comment by simlei** [comment]
Ok, I'll assign myself.

**Comment by simlei** [comment]
Done as of https://github.com/jcryptool/crypto/commit/bb30092d4e18605278e59df2aa947e9c4959d585 and https://github.com/jcryptool/core/commit/a3f7e9ef578f10f35feb3c4a01b9ad24d02cc26b

On my linux machine the links are still not opened in an external browser window; however, when explicitely clicking the context menu "open link in new window" entry, it does also not work. this seems to be a bug in the eclipse system that underlies the help.

On my Windows machine, this works now.

I have a solution concept for this for continued usage of the eclipse browser; it would involve rewriting these links to talk back to JCrypTool (i.e. a link would look like this: `http://localhost:<JCT-owned-port>/open-externally/<encoded-url>`). JCrypTool would decode the URL and properly talk to the OS, asking for opening the URL in a browser window.

The second idea I just discovered is, to use an external browser by default, where all these things work out of the box. The question is, how much better than in the eclipse browser? I suspect, better, and the user feels more comfortable with their own browser. This discussion should take place here: https://github.com/jcryptool/core/issues/208

I have archived the intermediate results of the link target replacement here:
- archive including the bash script, commented with the regular expressions used: 
[linkreplacement.zip](https://github.com/jcryptool/core/files/4759747/linkreplacement.zip)
- file that shows all external links that were augmented with `target="_blank"`: 
[linktargets.txt](https://github.com/jcryptool/core/files/4759749/linktargets.txt)

the `linktargets.txt` could be useful for later checking whether we have dead links somewhere.

**Comment by grthor** [comment]
As this task is finished, I think we can close this issue or are there any reasons to let it open?
