### ISSUE TITLE
Fix problem view

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#198]
The problem view does currently not work. Planned is a feedback button in the top toolbar that, if present, zips with the feedback the errors in the problem view.

**Comment by grthor** [comment]
The error log is often referenced in the online-help. The exact places I do not know, but this should be fixed.

Since the error log should be changed to a tool that does not show the stacktraces to the user (he could not fix them, so why show them to him) but should send an error report to us, the descriptions should also be adjusted to this new use of the tool.

**Comment by grthor** [comment]
Removed from Final 1.0.0 Milestone because it won't be included in Release 1.0.0.

**Comment by simlei** [comment]
The problem view seems to just have been removed from the eclipse bundles. It was a PDE artifact anyways. Since it is impossible to "just reactivate" it, this won't fix.
