### ISSUE TITLE
Online help: Rework of the help menu structure / hierarchie

### ISSUE THREAD

**Issue by ejfschmittel** [jcryptool/core#206]
Issue Collection found going through JCryptool mostly relating to the help menu.

- ~links on welcome page don't open the help navigation correctly~
- rework of the help menu structure / hierarchie
- ~remove mention of error log view from view help & cheat sheet~

Detailed information in the pdf [JCryptool Issues.pdf](https://github.com/jcryptool/core/files/4721745/JCryptool.Issues.pdf)

**Comment by grthor** [comment]
I replaced the error log view with the frequency analysis plugin in de and en.
This change will be in the weekly build on saturday.

**Comment by grthor** [comment]
The help navigation will be correctly opened: https://github.com/jcryptool/core/commit/70ee3197fdcbe4411ec818109e7884de7672d976

The problems were "mistakes" in the links. Instead of a generic `$nl$` which eclipse replaces automatically with the users language the language was hard coded with `nl/de` or `nl/en`. Replacing all `nl/de` and `nl/en` with `$nl$` fixed the problem.

![open](https://user-images.githubusercontent.com/20046726/83944437-c9aabe80-a803-11ea-801d-1fcd85e30de3.gif)

**Comment by grthor** [comment]
I noticed that `nl/de` and `nl/en` is used in several other places (some toc.xml and context.xml). I changed the occurences to `$nl$` and tested the functionality of the edited parts. In all cases the functionality improved. 

To give an example: The registration of the context help does not work 100% with `nl/de`. Only with `$nl$` the help get registered to the correct position in the content tree.

<img width="536" alt="wrong" src="https://user-images.githubusercontent.com/20046726/83946170-5f981680-a80f-11ea-817d-cfee11bda8d0.PNG">

I fixed all occurences of `nl/de` and `nl/en`: 
- https://github.com/jcryptool/core/commit/667cdf75e9c6f9ce8e4738a55190458afbc4875d
- https://github.com/jcryptool/core/commit/7865e498fcad658329fa4d7e82b80c17e36b3d1f
- https://github.com/jcryptool/crypto/commit/32fd757fd7b1b50aa227917719dc208531cc4b89
