### ISSUE TITLE
Help: use system browser by default? 

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#208]
Because of continued problems with the Eclipse browser, e.g. under Linux with target="_blank" anchors, I looked around a bit more and found that we actually have an option to use the OS browser for the help!

![help-external-browser](https://user-images.githubusercontent.com/982379/84286648-43fa7c00-ab3f-11ea-8fbf-466d89f9be98.gif)

I think this is better than the built-in eclipse browser but would not say I'm completely sure because we have never tested this. Because of that, let's all switch out JCT for a while to this option -- see animation -- and test it out?

Possibilities:
- ship this setting (external browser) for the systems where external links still not work -- like linux.
- ship this setting to all machines
- don't use the system browser, leave everything as is and fix https://github.com/jcryptool/core/issues/197 for linux in another way

Opinions?

**Comment by simlei** [comment]
do it on all OS

**Comment by grthor** [comment]
What is the current status on this? I know there was  a commit that added "target=_blank" to all external links. Does this fixes the problem with the not working links on all OSs? If yes, we could close this issue, because we fixed it. If not, I would prefer to revert the commit with the "target=_blank" and change the settings in the eclipse to open all Links in the systems default browser, because I think this is a cleaner solution.
