### ISSUE TITLE
AbstractAlphabet refactoring

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#23]
The abstract class AbstractAlphabet needs refactoring. Maybe this class can be removed/ replaced completely. So far, all methods in this class are deprecated.

**Comment by simlei** [comment]
I will look into the deprecations - I took a stab at this already in 2013 but gave up in the middle of it. I have not had much complaints with the alphabet storage and recall implementing various fixes so that it works smoothly with at all the classic algorithms over different locale-language-settings.

**Comment by simlei** [comment]
It seems, time has deemed the existing AbstractAlphabet implementation as worthy of making it into 1.0.0. Refactoring it would affect the interfaces of many plugins.
