### ISSUE TITLE
problem in launching JCrypTool from the source code

### ISSUE THREAD

**Issue by RuilinYang-beta** [jcryptool/core#246]
Hi, I'm having problems launching JCrypTool, most of the errors stem from `the import org.bouncycastle cannot be resolved`, as the picture here shows: 
![image](https://user-images.githubusercontent.com/21099652/117507744-c5dd6a00-af87-11eb-9e37-3222fc407ec5.png)

I am using jdk 16 and maven 3.6.3. 
I thought of two solutions, one is adding a bouncycastle dependency in the pom of the project `org.jcryptool.releng` in the hope that it will be inherited to all the children projects, as the picture shows, but it doesn't work; 
![image](https://user-images.githubusercontent.com/21099652/117508092-4b611a00-af88-11eb-8315-cc971a778341.png)
the other is to download the JARs of bouncycastle and add them to the build path of `org.jcryptool.releng`, but somehow there is no "Java Build Path" configuration for this project. 

I've run out of ideas and need some help. Many thanks.

**Comment by RuilinYang-beta** [comment]
I find manually adding the JAR of Bouncy Castle provider to the build path of the project `org.bouncycastle` helps to solve `the import org.bouncycastle cannot be resolved` error in `scr` folder (though there's still error in `META-INF` folder), but this is surely not the solution as there are too many children projects to add JARs one by one. 
![image](https://user-images.githubusercontent.com/21099652/117509487-9f6cfe00-af8a-11eb-9a33-f875e39757fb.png)

**Comment by simlei** [comment]
Hi, 

admirable effort, getting that far in debugging the issue :)
I fixed the issue now — the problem was that we changed the way bouncycastle was integrated into our target; also, `org.apache.commons.codec` was not in our core feature as it should be.

**Perform a `git pull` on the `core` repository for this to work.**

If you _refresh the target platform_ now, and _refresh your run configuration_ which embodies it, you should be fine. Alternatively, you could re-run the JCrypTool setup guide with a different path for the git repositories. 

**Refresh target platform**: Open `org.jcryptool.core.target/org.jcryptool.core.target.target` and click on "Refresh target platform"
**Refresh Run configuration**: Click on the drop down menu of the green "Run" icon in the eclipse toolbar. Click `Run Configurations...`. Locate the `jcryptool.product` entry on the left. Delete it via its context menu. Go to the project `org.jcryptool.product`, select the `jcryptool.product` file, "Synchronize..." and "Start a RCP Application".

This is the "all steps included" process to react to the change in a target platform from git upstram in an eclipse workspace, sorry this is so convoluted ^^. Hope this helps!

**Comment by RuilinYang-beta** [comment]
After going over the setup process, I can launch JCrypTool from the source code. Thanks for such a quick response!  :D

**Comment by simlei** [comment]
I'd like to ask a few things about how and where your interest in JCT stems from as I'm interested in people who get hands-on with a repository like ours without prior guidance, like yourself:
- Where do you come from, educationally speaking?
- How have you noticed JCrypTool?
- Are you interested in join the voluntary development team of JCT?

Thanks already :)

**Comment by RuilinYang-beta** [comment]
> I'd like to ask a few things about how and where your interest in JCT stems from as I'm interested in people who get hands-on with a repository like ours without prior guidance, like yourself:
> 
> * Where do you come from, educationally speaking?
> * How have you noticed JCrypTool?
> * Are you interested in join the voluntary development team of JCT?
> 
> Thanks already :)

I'll be glad to share my information if it helps you and JCT in some ways. 

* I am a 3rd-year Bachelor student in Technical Computer Science at University of Twente, Netherlands. 
* It's my Bachelor's assignment is to design and implement Searchable Encryption scheme(s) for JCT.
* Right now I'm a bit unsure about the last question :P My current goal is to finish the bachelor assignment and graduate smoothly.

**Comment by simlei** [comment]
Thanks for the info!

> * It's my Bachelor's assignment is to design and implement Searchable Encryption scheme(s) for JCT.

Interesting! Let us know if you think you need guidance on technical or UI design aspects of that: https://gitter.im/dschadow/jcryptool . You could also let us know there what you think of the already existing plugin (visualization) for Homomorphic Encryption which I think is at least somewhat related to that topic.
